---
# tasks file for preparing_hosts
- name: Set timezone to {{ tz_name }}
      community.general.timezone:
        name: "{{ tz_name }}"

- name: Run  apt update cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

- name: Install Node requirements
  ansible.builtin.apt:
    name: 
      - sudo 
      - curl
      - openssl
      - tar
      - socat
      - conntrack
      - ebtables
      - ipset
    state: present

- name: Download terminal based UI K9s   
  become: false
  ansible.builtin.unarchive:
    src: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
    dest: "{{ home_dir }}"   
    remote_src: yes 